SET TRANSACTION ISOLATION LEVEL 
-- READ UNCOMMITTED
-- READ COMMITTED
-- REPEATABLE READ
SERIALIZABLE
;

START TRANSACTION;

SELECT * FROM USER;
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, PHONE, CRTD_TMS, UPDT_TMS) 
 VALUES ('Priscilla1', 'Holden1', 'holden1@bigroi.by', '+375294444444', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
UPDATE  USER SET FIRST_NAME='Priscilla 2' WHERE USER_ID=17;

COMMIT;

SELECT * FROM PURCHASE_ORDER;

SELECT * FROM PURCHASE_ORDER_PRODUCT;

SELECT * FROM PURCHASE_ORDER;

SELECT CODE, QUANTITY, PRICE, NAME FROM PRODUCT WHERE CODE=20;

DELETE FROM PURCHASE_ORDER_PRODUCT WHERE ORDER_ID IN (17, 18);
DELETE FROM PURCHASE_ORDER WHERE ORDER_ID IN (17, 18);



START TRANSACTION;

INSERT INTO PURCHASE_ORDER(USER_ID, DLRY_ADDR_ID, DLRY_DATE, CRTD_TMS)
VALUES (2, 1, '2017-06-27', CURRENT_TIMESTAMP);

SELECT LAST_INSERT_ID();

INSERT INTO PURCHASE_ORDER_PRODUCT(ORDER_ID, PRODUCT_CODE, PRODUCT_PRICE, PRODUCT_QUANTITY)
VALUES (LAST_INSERT_ID(), 20, (SELECT PRICE FROM PRODUCT WHERE CODE=20), 3);

UPDATE PRODUCT SET QUANTITY=QUANTITY - 3 WHERE CODE=20;

SELECT * FROM PRODUCT WHERE CODE=20;

COMMIT;




ROLLBACK;