CREATE TABLE `USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` char(80) NOT NULL,
  `LAST_NAME` char(100) DEFAULT NULL,
  `EMAIL` char(250) DEFAULT NULL,
  `CRTD_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDT_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PHONE` varchar(40) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

CREATE TABLE `USER_ADDRESS` (
  `ADDR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STREET_ADDR` varchar(400) DEFAULT NULL,
  `CITY` char(100) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ADDR_ID`),
  KEY `USER_ADDRESS_USER_FK` (`USER_ID`),
  CONSTRAINT `USER_ADDRESS_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `PRODUCT` (
  `CODE` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` char(200) CHARACTER SET utf8 NOT NULL,
  `PRICE` decimal(10,0) NOT NULL,
  `DESCRIPTION` varchar(500) CHARACTER SET utf8 DEFAULT NULL,
  `QUANTITY` int(11) DEFAULT '0',
  `CRTD_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDT_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

CREATE TABLE `PURCHASE_ORDER` (
  `ORDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `STATUS_CD` int(11) NOT NULL DEFAULT '1',
  `DLRY_ADDR_ID` int(11) NOT NULL,
  `DLRY_DATE` date NOT NULL,
  `DLRY_TIME_FROM` time DEFAULT NULL,
  `DLRY_TIME_TO` time DEFAULT NULL,
  `ADDL_INFO` varchar(300) DEFAULT NULL,
  `CRTD_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDT_TMS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_ID`),
  KEY `PURCHASE_ORDER_USER_FK` (`USER_ID`),
  CONSTRAINT `PURCHASE_ORDER_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8;

CREATE TABLE `PURCHASE_ORDER_PRODUCT` (
  `ORDER_ID` int(11) NOT NULL,
  `PRODUCT_CODE` int(11) NOT NULL,
  `PRODUCT_QUANTITY` int(11) NOT NULL,
  `PRODUCT_PRICE` decimal(10,0) DEFAULT NULL,
  `DISCOUNT` decimal(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ORDER_ID`,`PRODUCT_CODE`),
  KEY `PURCHASE_ORDER_PRODUCT_PRODUCT_FK` (`PRODUCT_CODE`),
  CONSTRAINT `PURCHASE_ORDER_PRODUCT_PRODUCT_FK` FOREIGN KEY (`PRODUCT_CODE`) REFERENCES `PRODUCT` (`CODE`),
  CONSTRAINT `PURCHASE_ORDER_PRODUCT_PURCHASE_ORDER_FK` FOREIGN KEY (`ORDER_ID`) REFERENCES `PURCHASE_ORDER` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


